### PR TITLE
Support Laravel 10

### PR DESCRIPTION
**Pull request by hungthai1401**
Hi there,

I wasn't sure about how you'd handle bumping major version of a package & Laravel, hopefully this PR helps to save some time for updating to Laravel 10.

### CODE REVIEW

**Comment by bezhermoso** [comment]
Thanks, I'll have to read up what's new with Laravel 10 and see if there is more that should be done. At the very least, looks like it would need to be a major version release due to Composer dependency bumps.

**Comment by hungthai1401** [comment]
@bezhermoso I got it. Tell me if you have any suggestions

**Comment by hungthai1401** [comment]
@bezhermoso thanks, when will we release new version?

**Comment by bezhermoso** [comment]
@hungthai1401 Apologies for the delay, I just cut a release alongside a few additional rule support & fix: https://github.com/square/laravel-hyrule/releases/tag/3.0.0

**Comment by hungthai1401** [comment]
@bezhermoso thank you so much

**Pull request merged**
